### PR TITLE
Added logic to enable/disable pan gesture recognizer for specific controllers

### PR DESCRIPTION
**Pull request by ibarisic05**
Added logic to enable/disable pan gesture recognizer states for left or right  controller. It can work with both controllers.

### CODE REVIEW

**Comment by kaorimatz** [comment]
Hi @ibarisic05,

Thank you very much for your interest in this project. 

You can simply disable an edge pan gesture recognizer by setting the gesture recognizer's `enabled` property to false. Does this serve your purpose?

```
drawerController.leftDrawerOpenWithScreenEdgePanGestureRecognizer.enabled = false
drawerController.rightDrawerOpenWithScreenEdgePanGestureRecognizer.enabled = false
```

**Comment by ibarisic05** [comment]
Hi @kaorimatz,
This is exactly what I need. Thank you for info.

**Comment by kaorimatz** [comment]
It’s my pleasure!
If you are happy with this approach, can you please close this pr to keep the issue tracker clean?

**Comment by ibarisic05** [comment]
Yep.. Sry, forgot.

**Comment by kaorimatz** [comment]
No problem, Thanks!

**Pull request closed without merging**
